import type { FiltersResponse, Statement } from "@/types";

export const mockStatements: Statement[] = [
  {
    id: 1,
    vyrok: "Inflácia potravín na Slovensku bola vlani najvyššia za posledných desať rokov.",
    vyhodnotenie: "Pravda",
    odovodnenie:
      "Medziročný rast cien potravín v roku 2023 skutočne dosiahol najvyššiu úroveň v sledovanom desaťročí podľa údajov Štatistického úradu.",
    oblast: "Ekonomika",
    datum: "2024-02-14",
    meno: "Robert Fico",
    strana: "Smer",
  },
  {
    id: 2,
    vyrok: "Nemocnica v Banskej Bystrici stále nemá právoplatné stavebné povolenie.",
    vyhodnotenie: "Pravda",
    odovodnenie:
      "V čase výroku nebolo stavebné povolenie právoplatné, čo potvrdzovali aj verejné dokumenty rezortu zdravotníctva.",
    oblast: "Zdravotníctvo",
    datum: "2024-03-09",
    meno: "Milan Majerský",
    strana: "KDH",
  },
  {
    id: 3,
    vyrok: "Slovensko minulý rok vyčerpalo z plánu obnovy viac peňazí ako Česko.",
    vyhodnotenie: "Nepravda",
    odovodnenie:
      "Česká republika mala ku koncu sledovaného obdobia vyšší objem potvrdených platieb aj míľnikov než Slovensko.",
    oblast: "Eurofondy",
    datum: "2024-01-25",
    meno: "Richard Sulík",
    strana: "SaS",
  },
  {
    id: 4,
    vyrok: "Štát už dnes stavia všetky tri úseky diaľnice D1 na východe.",
    vyhodnotenie: "Nepravda",
    odovodnenie:
      "Rozostavaný bol iba jeden z uvádzaných úsekov, pri ďalších dvoch ešte neprebehlo odovzdanie staveniska.",
    oblast: "Doprava",
    datum: null,
    meno: "Peter Pellegrini",
    strana: "Hlas",
  },
  {
    id: 5,
    vyrok: "Priemerný plat učiteľov presiahol 2 000 eur mesačne.",
    vyhodnotenie: "Nepravda",
    odovodnenie:
      "Priemerné mzdy pedagogických zamestnancov boli podľa rezortu školstva nižšie než uvádzaná suma.",
    oblast: "Školstvo",
    datum: "2024-04-11",
    meno: "Igor Matovič",
    strana: "OĽaNO",
  },
  {
    id: 6,
    vyrok: "Cez nové eurofondy už prišlo na účty samospráv viac než miliarda eur.",
    vyhodnotenie: "Nepravda",
    odovodnenie:
      "V čase výroku nebola suma pre samosprávy ani zďaleka na úrovni jednej miliardy eur.",
    oblast: "Samospráva",
    datum: null,
    meno: "Matúš Šutaj Eštok",
    strana: "Hlas",
  },
  {
    id: 7,
    vyrok: "Nezamestnanosť mladých na Slovensku klesla na historické minimum.",
    vyhodnotenie: "Zavádzajúce",
    odovodnenie:
      "Miera nezamestnanosti mladých síce klesla, no historicky boli zaznamenané aj nižšie hodnoty v predpandemickom období.",
    oblast: "Práca",
    datum: "2024-02-02",
    meno: "Michal Šimečka",
    strana: "PS",
  },
  {
    id: 8,
    vyrok: "Všetky školy už majú zabezpečeného psychológa alebo školského podporného tímu.",
    vyhodnotenie: "Zavádzajúce",
    odovodnenie:
      "Podporné tímy sa rozšírili, ale systém nepokrýval všetky školy a časti služieb boli iba zdieľané.",
    oblast: "Školstvo",
    datum: null,
    meno: "Branislav Gröhling",
    strana: "SaS",
  },
  {
    id: 9,
    vyrok: "Štát zastropoval ceny plynu pre všetky domácnosti až do konca roka 2026.",
    vyhodnotenie: "Zavádzajúce",
    odovodnenie:
      "Regulácia sa týkala len časti odberateľov a obdobie garancie nebolo nastavené tak široko, ako výrok naznačuje.",
    oblast: "Energetika",
    datum: "2024-05-19",
    meno: "Robert Kaliňák",
    strana: "Smer",
  },
  {
    id: 10,
    vyrok: "Budúci rok nebude ani jeden nový daňový odvod pre živnostníkov.",
    vyhodnotenie: "Zavádzajúce",
    odovodnenie:
      "Vláda síce neohlásila novú samostatnú daň, ale navrhované zmeny v odvodoch by časť živnostníkov zasiahli.",
    oblast: null,
    datum: null,
    meno: "Mária Kolíková",
    strana: "SaS",
  },
  {
    id: 11,
    vyrok: "Vláda má pripravený plán na skrátenie čakacích lehôt pri onkologických vyšetreniach o polovicu.",
    vyhodnotenie: "Neoveriteľné",
    odovodnenie:
      "Verejne dostupné dokumenty neobsahovali konkrétny plán s jasnými opatreniami a termínmi, preto nebolo možné výrok spoľahlivo potvrdiť.",
    oblast: "Zdravotníctvo",
    datum: "2024-06-01",
    meno: "Denisa Saková",
    strana: "Hlas",
  },
  {
    id: 12,
    vyrok: "Kabinet má pripravený plán, ktorý má skrátiť čakanie na onkologické vyšetrenia na polovicu.",
    vyhodnotenie: "Neoveriteľné",
    odovodnenie: null,
    oblast: "Zdravotníctvo",
    datum: null,
    meno: "Tomáš Drucker",
    strana: "Hlas",
  },
  {
    id: 13,
    vyrok: "Európska komisia zvažuje osobitný fond pre ochranu hranice s Ukrajinou.",
    vyhodnotenie: "Neoveriteľné",
    odovodnenie:
      "Diskusia o nových finančných nástrojoch prebiehala neformálne, no bez verejného návrhu alebo potvrdeného harmonogramu.",
    oblast: null,
    datum: "2024-02-28",
    meno: "Michal Šimečka",
    strana: "PS",
  },
  {
    id: 14,
    vyrok: "Na severe Slovenska dnes chýba približne 300 pediatrov.",
    vyhodnotenie: "Pravda",
    odovodnenie:
      "Odhady profesijných združení a regionálnych poisťovní ukazovali dlhodobý deficit pediatrov približne v tejto výške.",
    oblast: "Zdravotníctvo",
    datum: null,
    meno: "Milan Majerský",
    strana: "KDH",
  },
  {
    id: 15,
    vyrok: "Na severe Slovenska chýbajú asi tri stovky pediatrov.",
    vyhodnotenie: "Pravda",
    odovodnenie:
      "Výrok parafrázuje rovnaké odhady nedostatku pediatrov v severných regiónoch, ktoré sa pohybovali okolo tristo miest.",
    oblast: "Zdravotníctvo",
    datum: null,
    meno: "Veronika Remišová",
    strana: "OĽaNO",
  },
];

export const mockFilters: FiltersResponse = {
  strany: ["Hlas", "KDH", "OĽaNO", "PS", "SaS", "Smer"],
  oblasti: [
    "Doprava",
    "Ekonomika",
    "Energetika",
    "Eurofondy",
    "Priemysel",
    "Práca",
    "Samospráva",
    "Zdravotníctvo",
    "Školstvo",
  ],
  mena: [
    "Branislav Gröhling",
    "Denisa Saková",
    "Igor Matovič",
    "Mária Kolíková",
    "Matúš Šutaj Eštok",
    "Michal Šimečka",
    "Milan Majerský",
    "Milan Uhrík",
    "Peter Pellegrini",
    "Richard Sulík",
    "Robert Fico",
    "Robert Kaliňák",
    "Tomáš Drucker",
    "Veronika Remišová",
  ],
  verdicts: ["Pravda", "Nepravda", "Zavádzajúce", "Neoveriteľné"],
  date_range: {
    min: "2024-01-25",
    max: "2024-06-01",
  },
};
